stages:
  - stage:release

# This version is important! See https://github.com/semantic-release/gitlab/issues/139
image: node:12.14.1

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

# This selects only refs matching master
.only_semantic_release: &only_semantic_release
  only:
    - master

step:release:semantic_release:
  <<: *only_semantic_release
  when: manual
  stage: stage:release
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - echo "$GITLAB_USER_EMAIL"
    - echo "$GITLAB_USER_NAME"
    - echo "$CI_GIT_TOKEN"
  script:
    - npm i --non-interactive --pure-lockfile
    - npm run semantic-release
